name: Pull Request Labeler

on:
  pull_request_target:

permissions:
  contents: read

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/labeler@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yaml
          sync-labels: true
