name: Lint (locales)

on:
  push:
    branches:
      - taiyme
    paths:
      - .github/workflows/lint-locales.yaml
      - locales/**/*
  pull_request:
    paths:
      - .github/workflows/lint-locales.yaml
      - locales/**/*

jobs:
  lint_locales:
    name: Lint locales
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Enable corepack
        run: |
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: Check Verify
        working-directory: locales
        run: |
          node verify.js
